format = """
$directory\
$git_branch\
$git_status\
$nodejs\
$rust\
$golang\
$python\
$kubernetes\
$cmd_duration\
$time\
$line_break\
$character"""

add_newline = false

[character]
success_symbol = "[❯](bold #98BB6C)"
error_symbol   = "[❯](bold #C34043)"
vimcmd_symbol  = "[❮](bold #E6C384)"

[directory]
style = "fg:#1F1F28 bg:#7E9CD8"
format = "[](fg:#7E9CD8)[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[git_branch]
symbol = ""
style = "fg:#1F1F28 bg:#76946A"
format = '[](fg:#7E9CD8 bg:#76946A)[ $symbol$branch ]($style)'

[git_status]
style = "fg:#1F1F28 bg:#76946A"
format = '[$all_status$ahead_behind ]($style)'

[nodejs]
symbol = ""
style = "fg:#1F1F28 bg:#E6C384"
format = '[](fg:#76946A bg:#E6C384)[ $symbol($version) ]($style)'

[rust]
symbol = ""
style = "fg:#1F1F28 bg:#E6C384"
format = '[](fg:#76946A bg:#E6C384)[ $symbol($version) ]($style)'

[golang]
symbol = ""
style = "fg:#1F1F28 bg:#E6C384"
format = '[](fg:#76946A bg:#E6C384)[ $symbol($version) ]($style)'

[python]
symbol = ""
style = "fg:#1F1F28 bg:#E6C384"
format = '[](fg:#76946A bg:#E6C384)[ $symbol($pyversion) ]($style)'

[kubernetes]
disabled = false
symbol = "☸ "
format = '[ $symbol$context( \($namespace\)) ](fg:#957FB8)'

[[kubernetes.contexts]]
context_pattern = "(.{19}).{2,}"
context_alias = "$1…"

[cmd_duration]
min_time = 2_000
format = "[ 󱎫 $duration ](fg:#FFA066)"

[time]
disabled = false
time_format = "%T"
format = "[ $time ](fg:#7AA89F)"
